### ISSUE TITLE
Exception("Unsupported format char: %s in message %s (%i)" % (c, msg_name, msg_type))

### ISSUE THREAD

**Issue by gulp79** [OverloadUT/apm-dashware#1]
i'm testing your script, but i've always the same error with all my logs (Arducopter 3.3.2):

python sdlog2_dump2.py "logapm.bin" -f test.csv -m GPS -m ATT -m NTUN -m CTUN -m MODE -m CURR

Traceback (most recent call last):
  File "sdlog2_dump2.py", line 154, in <module>
    _main()
  File "sdlog2_dump2.py", line 79, in _main
    (columns, rows) = parser.process(filename)
  File "sdlog2parser.py", line 116, in process
    self.__parseMsgDescr()
  File "

sdlog2parser.py", line 187, in __parseMsgDescr
    raise Exception("Unsupported format char: %s in message %s (%i)" % (c, msg_name, msg_type))
Exception: Unsupported format char: d in message GRAW (171)

**Comment by OverloadUT** [comment]
I will check this out! Do you have an example log you could attach?

**Comment by gulp79** [comment]
Sure! These are two of the logs i've tried.
(i've zipped them because github dosn't accepts .bin)
[20160130 - logs.zip](https://github.com/OverloadUT/apm-dashware/files/120467/20160130.-.logs.zip)

**Comment by gulp79** [comment]
Using the .log file (instead of .bin) sdlog2_dump2.py runs ok (with -e option) but the resulting csv file is empty.
Using .log but without using the -e option i've:

c:\Program Files\Python>python.exe apm-dashware-master\sdlog2_dump.py "apm-dashware-master\2015.log" -f "apm-dashware-master\test.csv" -m GPS -m ATT -m NTUN -m CTUN -m MODE -m CURR
Traceback (most recent call last):
  File "apm-dashware-master\sdlog2_dump.py", line 154, in <module>
    _main()
  File "apm-dashware-master\sdlog2_dump.py", line 79, in _main
    (columns, rows) = parser.process(filename)
  File "c:\Program Files\Python\apm-dashware-master\sdlog2parser.py", line 110, in process
    bytes_read + self.__ptr, bytes_read + self.__ptr, head1, head2, self.MSG_HEAD1, self.MSG_HEAD2))
Exception: Invalid header at 0 (0x0): 34 0D, must be A3 95

**Comment by OverloadUT** [comment]
Hey, try now with the latest code! Looks like there were some changes to the .bin format, including a new datatype as well as a change to using microseconds rather than miliseconds. I just committed a change that addresses both of these.

**Comment by gulp79** [comment]
Great!! Thank you! Now seems all ok :+1:
